spring.application.name=demo
# Change 'ecotrack_db' if you used a different name in MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecotrack_db
spring.datasource.username=root
spring.datasource.password=virche22

# This automatically creates the table based on your ecotrackModel.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true